services:
  postgres-db:
    image: docker.io/bitnami/postgresql:16.1.0-debian-11-r15
    environment:
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - 5432:5432
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  adminer:
    image:  adminer
    ports:
      - 8880:8080
    depends_on:
      postgres-db:
        condition: service_healthy
        restart: true

    
  inference-webserver:
    image: mini_webserver
    command: bash /home/webserver.sh  8080
    ports:
      - 8080:8080
    volumes:
      - .:/home
    environment:
      - postgres_server=postgres-db
      - postgres_port=5432
      - postgres_password=postgres
      
      - postgres_db_name=isic_db
      - postgres_db_user=isic_db_user
      - postgres_db_password=isic_db_password
      
      - images_folder=images_folder
    depends_on:
      kafka:
        condition: service_healthy
        restart: true
      postgres-db:
        condition: service_healthy
        restart: true



  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8088:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      kafka:
        condition: service_healthy
        restart: true
    
    #volumes:
    #  - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
