apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inference
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.inference.name }}-service
  ports:
    - protocol: TCP
      port: {{ .Values.inference.service.port }}
      targetPort: 8080
