[tool.pylint.messages_control]
disable = ["R0801"]

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.isort]
profile = "black"
group_by_package = true
combine_as_imports = true
multi_line_output = 3