apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-persistance
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.data_persistance.name }}-service
  ports:
    - protocol: TCP
      port: {{ .Values.data_persistance.service.port }}
      targetPort: 8080
