apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.data_persistance.name }}-pvc
  namespace: {{ .Values.namespace }}
  #annotations:
  #  helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data_persistance.pvc.size }}