{
 "title": "isic skin cancer  classification  dashboard",
 "time": { "from": "2024-12-30T08:18:56.160Z", "to": "2025-02-01T02:54:27.049Z" },
 "templating": {
  "list": [
   {
    "name": "day",
    "query": "select to_char ( date, 'YYYY-MM-DD' ) from curr_means"
   },
   {
    "name": "tab_feature",
    "query": "SELECT column_name as tab_features\n  FROM information_schema.columns\n WHERE table_schema = 'public'\n   AND table_name   = 'drift'\n   AND (column_name='clin_size_long_diam_mm'\n        OR column_name LIKE 'tbp%')"
   },
   {
    "name": "feature",
    "query": "SELECT column_name as feature\n  FROM information_schema.columns\n WHERE table_schema = 'public'\n   AND table_name   = 'drift'\n   AND (column_name NOT IN ('date','index' ) )"
   },
   { "name": "color", "query": "r,b,g" }
  ]
 },
 "panels": [
  {
   "title": "Isic Skin Cancer Misses ",
   "type": "alertlist",
   "description": "Skin cancer misses (score < 0.5)",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Image Histograms per day and color",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT bin_label,\n       AVG(value) as curr\nFROM curr_hists\nWHERE date='$day'\n      AND color='$color'\nGROUP BY bin_label\nORDER BY CAST(bin_label AS REAL)"
    },
    {
     "rawSql": "SELECT bin_label,\n       AVG(value) as ref\nFROM reference_hist\nWHERE color='$color'\nGROUP BY bin_label\nORDER BY CAST(bin_label AS REAL)"
    }
   ]
  },
  {
   "title": "ROC  per day",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select fx as fpr,  ty as tpr from rocs \nWHERE date='$day'"
    },
    {
     "rawSql": "SELECT  auc FROM aucs \nWHERE date='$day'"
    }
   ]
  },
  {
   "title": "AUCs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "targets": [
    { "rawSql": "SELECT date, auc FROM aucs " }
   ]
  },
  {
   "title": "Images red color mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  curr_means.date,\r\n  curr_means.img_r_mean as curr_mean,\r\n  curr_stds.img_r_mean as curr_std\r\nFROM\r\n  curr_means\r\n  LEFT JOIN curr_stds on curr_stds.date = curr_means.date"
    },
    {
     "rawSql": "SELECT ref_means.img_r_mean as ref_mean,\r\n       curr_means.date as date\r\nFROM ref_means, ref_stds, curr_means"
    }
   ]
  },
  {
   "title": "Images blue color mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  curr_means.date,\r\n  curr_means.img_b_mean as curr_mean,\r\n  curr_stds.img_b_mean as curr_std\r\nFROM\r\n  curr_means\r\n  LEFT JOIN curr_stds on curr_stds.date = curr_means.date"
    },
    {
     "rawSql": "SELECT ref_means.img_b_mean as ref_mean,\r\n       curr_means.date as date\r\nFROM ref_means, ref_stds, curr_means"
    }
   ]
  },
  {
   "title": "Images green color mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  curr_means.date,\r\n  curr_means.img_g_mean as curr_mean,\r\n  curr_stds.img_g_mean as curr_std\r\nFROM\r\n  curr_means\r\n  LEFT JOIN curr_stds on curr_stds.date = curr_means.date"
    },
    {
     "rawSql": "SELECT ref_means.img_g_mean as ref_mean,\r\n       curr_means.date as date\r\nFROM ref_means, ref_stds, curr_means"
    }
   ]
  },
  {
   "title": "Tab Features Drift Per Day",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  date,\n\"clin_size_long_diam_mm\",\n\"tbp_lv_A\",\n\"tbp_lv_Aext\",\n\"tbp_lv_B\",\n\"tbp_lv_Bext\",\n\"tbp_lv_C\",\n\"tbp_lv_Cext\",\n\"tbp_lv_H\",\n\"tbp_lv_Hext\",\n\"tbp_lv_L\",\n\"tbp_lv_Lext\",\n\"tbp_lv_areaMM2\",\n\"tbp_lv_area_perim_ratio\",\n\"tbp_lv_color_std_mean\",\n\"tbp_lv_deltaA\",\n\"tbp_lv_deltaB\",\n\"tbp_lv_deltaL\",\n\"tbp_lv_deltaLBnorm\",\n\"tbp_lv_eccentricity\",\n\"tbp_lv_minorAxisMM\",\n\"tbp_lv_nevi_confidence\",\n\"tbp_lv_norm_border\",\n\"tbp_lv_norm_color\",\n\"tbp_lv_perimeterMM\",\n\"tbp_lv_radial_color_std_max\",\n\"tbp_lv_stdL\",\n\"tbp_lv_stdLExt\",\n\"tbp_lv_symm_2axis\",\n\"tbp_lv_symm_2axis_angle\",\n\"tbp_lv_x\",\n\"tbp_lv_y\",\n\"tbp_lv_z\"\n FROM drift\nWHERE date = '$day'"
    }
   ]
  },
  {
   "title": "Tab Feature  Drift Over Days",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT  date, \"$tab_feature\"\nFROM drift"
    }
   ]
  }
 ]
}