apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 3      # number of previous versions to keep
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      initContainers:
      - name: repo-clone
        image: alpine/git:v2.49.1
        command: ["sh"]

        args:
          - -c
          - >-
              cd /home &&
              git clone $code_repo repo_code &&
              cd repo_code &&
              git checkout $repo_commit_id
        env:
        
          - name: code_repo
            valueFrom:
                configMapKeyRef:
                  name: system-cfgmap
                  key: code_repo
          - name: repo_commit_id
            valueFrom:
                configMapKeyRef:
                  name: system-cfgmap
                  key: repo_commit_id
        

        # args:
        #   - -c
        #   - >-
        #       cd /home &&
        #       git clone {{ .Values.code_repo }} repo_code
        
        volumeMounts:
        - mountPath: "/home"
          name: homedir

      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: Never
        command: ["bash"]
        args: ["/home/repo_code/inference_webserver/backend/run_backend.sh"]
        ports:
          - containerPort: 8080
        env:
        - name: kafka_server
          value: {{ .Values.kafka.server }}
        - name: kafka_topic_name
          value: {{ .Values.kafka.topic_name }} 
        - name: kafka_topic_num_partitions
          value: "{{ .Values.kafka.topic_num_partitions }}"
        - name: kafka_topic_replication_factor
          value: "{{ .Values.kafka.topic_replication_factor }}"
        - name: isic_schema_file
          value: {{ .Values.backend.isic_schema_file }}
        
        volumeMounts:
        - mountPath: "/home"
          name: homedir
        
      volumes: ###
        - name: homedir
          emptyDir: {}
      