namespace: isic-skin-cancer-classification

code_repo: https://github.com/Mahdi-Moalla/isic-skin-cancer-classification

kafka:
  server: "kafka-service-broker:9092"
  topic_name: "isic_topic"
  topic_num_partitions: 1
  topic_replication_factor: 1

gateway:
  name: inference-webservice

postgres_db:
  host: airflow-service-postgresql
  port: 5432
  db_name: inference_webserver_db
  existing_db_secret:
    name: inference-webserver-db-secret
    usernameKey: username
    passwordKey: password


mlflow:
  server: http://mlflow-service:5000
  experiment_name: isic-skin-cancer-classification

inference:
  name:  isic-inference
  image: nvcr_pytorch_tensorrt_mod:latest
  service_image: webserver:latest
  service:
    port: 8080
  model:
    registry:
      model_name: isic-skin-cancer-classification-model
      version: 1
  py_artifacts_run_id: b07ab1407928453e8af1b9530083be95


backend:
  name: isic-backend
  image: webserver:latest
  isic_schema_file: isic_record.avsc
  service:
    port: 8080
  
data_persistance:
  name: isic-data-persistance
  image: webserver:latest
  service_image: webserver:latest
  images_folder: /home/images
  pvc:
   size:  5Gi
  service:
    port: 8080

