namespace: isic-skin-cancer-classification

code_repo: https://github.com/Mahdi-Moalla/isic-skin-cancer-classification

kafka:
  server: "kafka-service-broker:9092"
  topic_name: "isic_topic"
  topic_num_partitions: 1
  topic_replication_factor: 1

isic_schema_file: isic_record.avsc


postgres_db:
  host: airflow-service-postgresql
  port: 5432
  db_name: inference_webserver_db
  existing_db_secret:
    name: inference-webserver-db-secret
    usernameKey: username
    passwordKey: password


mlflow:
  server: http://mlflow-service:5000
  experiment_name: isic-skin-cancer-classification

inference:
  name:  isic-inference
  image: nvcr_pytorch_tensorrt_mod:latest
  best_model:
    model_checkpoint_uri:  mlflow-artifacts:/1/d496d71a14544584913114655b6f6771/artifacts/best_finetune/best_finetune_0.ckpt
    model_def_uri: mlflow-artifacts:/1/22c2f1bcd7454418b8d1ef02b83d044d/artifacts/trainer/isic_model.py
    model_config_uri: mlflow-artifacts:/1/22c2f1bcd7454418b8d1ef02b83d044d/artifacts/trainer/config.py
    preprocessor_def_uri: mlflow-artifacts:/1/22c2f1bcd7454418b8d1ef02b83d044d/artifacts/data_preprocessor/preprocess_data.py


webserver:
  name: isic-webserver
  image: webserver:latest
  service:
    port: 8080
  
data_persistance:
  name: isic-data-persistance
  image: webserver:latest
  images_folder: /home/images
  pvc:
   size:  5Gi