services:
  postgres-db:
    image: docker.io/bitnami/postgresql:16.1.0-debian-11-r15
    environment:
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - 5432:5432

  adminer:
    image:  adminer
    ports:
      - 8080:8080