adminPassword: admin

extraEmptyDirMounts:
  - name: provisioning-datasources
    mountPath: /etc/grafana/provisioning/datasources
  - name: provisioning-dashboards
    mountPath: /etc/grafana/provisioning/dashboards
  - name: provisioning-dashboards-def
    mountPath: /etc/grafana/provisioning/dashboards_def
  - name: provisioning-tmp
    mountPath: /etc/grafana/provisioning/tmp
  - name: provisioning-alerting
    mountPath: /etc/grafana/provisioning/alerting


extraInitContainers:
  - name: repo-clone
    image: alpine/git:v2.49.1
    command: ["sh"]
    args:
      - -c
      - >-
          export tmp_dir=/etc/grafana/provisioning/tmp &&
          export data_sources=/etc/grafana/provisioning/datasources &&
          export dashboards=/etc/grafana/provisioning/dashboards &&
          export dashboard_def=/etc/grafana/provisioning/dashboards_def &&
          export alerts=/etc/grafana/provisioning/alerting &&
          cd $tmp_dir &&
          git clone $code_repo code_repo &&
          cd  code_repo &&
          cp monitoring/grafana/datasource.yml  $data_sources &&
          cp monitoring/grafana/dashboard_provider.yml $dashboards &&
          cp monitoring/grafana/dashboard_def.json $dashboard_def &&
          cp monitoring/grafana/alert.json $alerts
    env:
      - name: code_repo
        valueFrom:
          configMapKeyRef:
            name: system-cfgmap
            key: code_repo
      
    volumeMounts:
      - name: provisioning-datasources
        mountPath: /etc/grafana/provisioning/datasources
      - name: provisioning-dashboards
        mountPath: /etc/grafana/provisioning/dashboards
      - name: provisioning-dashboards-def
        mountPath: /etc/grafana/provisioning/dashboards_def
      - name: provisioning-tmp
        mountPath: /etc/grafana/provisioning/tmp
      - name: provisioning-alerting
        mountPath: /etc/grafana/provisioning/alerting
