apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.webserver.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.webserver.service.port }}
      targetPort: 8080
