# TODO:  fix http server addr and port (configmap ....)
apiVersion: v1
kind: Pod
metadata:
  name: data-download-pod
  namespace: isic-skin-cancer-classification
spec:
  restartPolicy: OnFailure
  containers:
    - name: base
      image: ubuntu_toolset:latest
      imagePullPolicy: Never
      command: ["bash"]
      args:
        - -c
        - >-
            mkdir /workspace/data/dataset/ &&
            echo $dataset_http_server &&
            echo $dataset_http_server_port &&
            wget http://$dataset_http_server:$dataset_http_server_port/train-image.hdf5 -O /workspace/data/dataset/train-image.hdf5 &&
            wget http://$dataset_http_server:$dataset_http_server_port/train-metadata.csv -O /workspace/data/dataset/train-metadata.csv &&
            echo "data download finished ..." 
      env:
      
        - name: dataset_http_server
          valueFrom:
              configMapKeyRef:
                name: training-pipeline-cfgmap
                key: dataset_http_server
        
        - name: dataset_http_server_port
          valueFrom:
              configMapKeyRef:
                name: training-pipeline-cfgmap
                key: dataset_http_server_port
        
      volumeMounts:
        - mountPath: "/workspace/data/"
          name: training-pipeline-volume
  volumes: ###
    - name: training-pipeline-volume ###
      persistentVolumeClaim: ###
        claimName: traininig-pipeline-pvc ###

