# TODO:  fix http server addr and port (configmap ....)
apiVersion: v1
kind: Pod
metadata:
  name: data-download-pod
  namespace: isic-skin-cancer-classification
spec:
  restartPolicy: OnFailure
  containers:
    - name: base
      image: busybox:latest
      command: ["sh"]
      args:
        - -c
        - >-
            mkdir -p /workspace/data/$(dataset_folder)/ &&
            echo $dataset_http_server &&
            echo $dataset_http_server_port &&
            wget $(original_dataset_http_server)/train-image.hdf5 -O /workspace/data/$(dataset_folder)/train-image.hdf5 &&
            wget $(original_dataset_http_server)/train-metadata.csv -O /workspace/data/$(dataset_folder)/train-metadata.csv &&
            echo "data download finished ..." 

      env:
      
        - name: original_dataset_http_server
          valueFrom:
              configMapKeyRef:
                name: training-pipeline-cfgmap
                key: original_dataset_http_server
        
        - name: dataset_folder
          valueFrom:
              configMapKeyRef:
                name: training-pipeline-cfgmap
                key: dataset_folder
        
      volumeMounts:
        - mountPath: "/workspace/data/"
          name: training-pipeline-volume
  volumes: ###
    - name: training-pipeline-volume ###
      persistentVolumeClaim: ###
        claimName: traininig-pipeline-pvc ###

