apiVersion: v1
kind: Pod
metadata:
  name: data-download-pod
  namespace: isic-skin-cancer-classification
spec:
  restartPolicy: OnFailure
  containers:
    - name: base
      image: ubuntu_toolset:latest
      imagePullPolicy: Never
      command: ["/bin/sh"]
      args:
        - -c
        - >-
            echo hello1 &&
            echo hello2 &&
            sleep 1000 
      
      volumeMounts:
        - mountPath: "/workspace/data/"
          name: training-pipeline-volume
  volumes: ###
    - name: training-pipeline-volume ###
      persistentVolumeClaim: ###
        claimName: traininig-pipeline-pvc ###

