apiVersion: v1
kind: Pod
metadata:
  name: trainer-pod
  namespace: isic-skin-cancer-classification
spec:
  restartPolicy: OnFailure
  containers:
    - name: base
      image: nvcr_pytorch_tensorrt_mod:latest
      imagePullPolicy: Never
      env:
        - name: code_repo
          valueFrom:
              configMapKeyRef:
                name: system-cfgmap
                key: code_repo
        - name: repo_commit_id
          valueFrom:
              configMapKeyRef:
                name: system-cfgmap
                key: repo_commit_id
      
        - name: preprocessed_dataset_folder
          valueFrom:
              configMapKeyRef:
                name: training-pipeline-cfgmap
                key: preprocessed_dataset_folder
          
      resources:
        limits:
          nvidia.com/gpu: 1
      command: ["bash"]
      #hostIPC: true
      #resources:
      #  requests:
      #    memory: "5Gi"
      #    ephemeral-storage: "2Gi"
      #  limits:
      #    memory: "5Gi"
      #    ephemeral-storage: "2Gi"
      args:
        - -c
        - >-
            nvidia-smi &&
            mkdir -p /workspace/data/work &&
            git clone $code_repo repo_code &&
            cd repo_code &&
            git checkout $repo_commit_id &&
            cd training_pipeline/trainer/ &&
            cp /etc/isic_config/*  .  &&
            python train.py /workspace/data/$(preprocessed_dataset_folder) /workspace/data/work

      volumeMounts:
        - mountPath: "/workspace/data"
          name: training-pipeline-volume
        - mountPath: "/mlflow/artifacts"
          name: mlflow-artifacts-volume
        - mountPath: /dev/shm
          name: shared-mem
        - mountPath: /etc/isic_config
          name: training-pipeline-json-defs-volume
  volumes: ###
    - name: training-pipeline-volume ###
      persistentVolumeClaim: ###
        claimName: traininig-pipeline-pvc ###
    - name: mlflow-artifacts-volume ###
      persistentVolumeClaim: ###
        claimName: mlflow-artifacts-pvc ###
    - name: shared-mem
      medium: Memory
      sizeLimit: 256Mi
    - name: training-pipeline-json-defs-volume
      configMap:
        name: training-pipeline-json-defs
        items:
        - key: config.json
          path: config.json
        - key: train_transform.json
          path: train_transform.json
        - key: val_transform.json
          path: val_transform.json
